version: "3.8"
services:
  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - user-net
      - sala-net
      - reserva-net
    depends_on:
      - usermicroservice
      - salamicroservice
      - reservamicroservice

  usermicroservice:
    build: User/user
    depends_on:
      - dbuser
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbuser:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - user-net

  salamicroservice:
    build: Sala/sala
    depends_on:
      - dbsala
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbsala:5432/salasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - sala-net

  reservamicroservice:
    build: Reserva/reserva
    depends_on:
      - dbreserva
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbreserva:5432/reservasdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - reserva-net

  dbuser:
    image: postgres:15
    container_name: dbuser
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - user-net
    volumes:
      - userdbdata:/var/lib/postgresql/data

  dbsala:
    image: postgres:15
    container_name: dbsala
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: salasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - sala-net
    volumes:
      - saladbdata:/var/lib/postgresql/data

  dbreserva:
    image: postgres:15
    container_name: dbreserva
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: reservasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - reserva-net
    volumes:
      - reservadbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - user-net
      - sala-net
      - reserva-net

networks:
  user-net:
  sala-net:
  reserva-net:

volumes:
  userdbdata:
  saladbdata:
  reservadbdata:
